### ISSUE TITLE
you cannot mention voice channels

### ISSUE THREAD

**Issue by Assassin-1234** [Snowflake107/youtube-together-bot#1]
I dont think line [41](https://github.com/Snowflake107/youtube-together-bot/blob/main/index.js#L41) goes with line [42](https://github.com/Snowflake107/youtube-together-bot/blob/main/index.js#L42) since you cannot mention voice channels, same goes in activity command.. its a useless statement

**Comment by menonkrishna57** [comment]
copy the id if the voice channel

**Comment by Assassin-1234** [comment]
> copy the id if the voice channel

try doing that, it wont send the mention but the channel name

**Comment by twlite** [comment]
Use `#!channelName`. Also, the channel can be mentioned with `<#channel_id>`

(channel is mentioned in this pic even tho it isnt rendered by discord client)
![image](https://user-images.githubusercontent.com/46562212/115010758-831afb80-9ecd-11eb-869b-51dd4265b573.png)

Current Image
![image](https://user-images.githubusercontent.com/46562212/115010864-a6de4180-9ecd-11eb-85f4-e0c10a08596e.png)
